config/routes.rb
# frozen_string_literal: true

Rails.application.routes.default_url_options[:host] = ENV["URL"] || "localhost:3000"

Rails.application.routes.draw do
  root to: "welcome#show"
  get "/home", to: "home#show"
  get "/sign_in" => "sessions#new", as: :sign_in
  resource :session, controller: "sessions", only: %i[new create destroy]

  namespace :manage do
    root to: "manage#show"
    get :switch_accounts, to: "switch_accounts#show", constraints: ->(req) { req.format == :js }

    resources :organizations, only: [] do
      get "dashboard", to: "dashboards#show"
      resources :employees, except: %i[show]
      namespace :settings do
        resource :organization, only: %i[edit update]
        resource :meta_data, only: %i[edit]
        resources :vessels, except: %i[index] do
          member do
            get :remove
          end
        end
      end
    end
  end

  if Rails.env.development? || Rails.env.test?
    post "session_without_csrf", to: "sessions#create_without_csrf"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Clearance::Controller
  include Authorization

  helper_method :current_organization

  def current_organization
    organization = current_user&.manages_organizations&.find_by(id: session[:current_organization_id])
    organization = current_user&.manages_organizations&.first unless organization.present?
    organization
  end

  rescue_from Pundit::NotAuthorizedError do
    redirect_unauthorized
  end

  protected

  def redirect_unauthorized
    redirect_to request.referrer || root_path, flash: { danger: "You are not authorized to perform this action." }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def body_classes
    [controller_name, action_name].join(" ")
  end
end

app/views/application/_base_modals.html.erb
<%= component "modal",
              id: "remote_modal",
              skip_header: true,
              content_classes: "modal__content modal__content--loading" %>

app/views/application/_favicons.html.erb
<!-- generics -->
<link rel="icon" href="/favicons/favicon-96x96.png" sizes="96x96">

app/views/application/_footer.html.erb
<footer>
  <div class="c-footer">
    <div class="l-container">
      <div class="l-row">
        <div class="l-col-xs-13 l-col-sm-18 l-col-sm-offset-1">
          <div class="l-row">
            <div class="c-footer__column l-col-xs-26 l-col-sm-spread">
              <h4>Explore</h4>
              <ul class="c-footer__links">
                <li><%= link_to "Courses", "#", class: "u-text-normal" %></li>
                <li><%= link_to "For Business", "#", class: "u-text-normal" %></li>
                <li><%= link_to "Teach on Seably", "#", class: "u-text-normal" %></li>
              </ul>
            </div>
            <div class="c-footer__column l-col-xs-26 l-col-sm-spread">
              <h4>Company</h4>
              <ul class="c-footer__links">
                <li><%= link_to "Mobile Apps", "#", class: "u-text-normal" %></li>
                <li><%= link_to "Privacy Policy", "#", class: "u-text-normal", target: "_blank" %></li>
                <li><%= link_to "Contact", "#", class: "u-text-normal" %></li>
              </ul>
            </div>
            <div class="c-footer__column l-col-xs-26 l-col-sm-spread">
              <h4>Social</h4>
              <ul class="c-footer__links">
                <li><%= link_to "Facebook", "https://www.facebook.com/SeablyTraining", target: "_blank", class: "u-text-normal" %></li>
                <li><%= link_to "LinkedIn", "https://linkedin.com/company/seably", target: "_blank", class: "u-text-normal" %></li>
                <li><%= link_to "Twitter", "https://twitter.com/SeablyTraining", target: "_blank", class: "u-text-normal" %></li>
                <li><%= link_to "Medium", "https://medium.com/seably", target: "_blank", class: "u-text-normal" %></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="c-footer__column l-col-xs-13 l-col-sm-6">
          <h4>Support</h4>
          <ul class="c-footer__links">
            <li><%= link_to "Chat with Us", "#", class: "u-text-normal", target: "_blank" %></li>
            <li><%= link_to "Help Center", "#", class: "u-text-normal", target: "_blank" %></li>
            <li><%= link_to "Business Partnership", "#", class: "u-text-normal", target: "_blank" %></li>
            <li><%= link_to "Book a Demo", "#", class: "u-text-normal", target: "_blank" %></li>
          </ul>
        </div>
      </div>
      <div class="l-row">
        <div class="l-col-xs-26 u-text-center">
          <h4>© <%= Time.now.year %>, Seably</h4>
          <ul>
            <li>Kungsgatan 4, SE-411 19,</li>
            <li>Gothenburg, Sweden</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/application/_modal_close.html.erb
<% action ||= "modal#hide" %>

<button type="button" class="modal__close" data-action="<%= action %>" title="Close">
  <svg class="icon icon--close"><use xlink:href="#icons-close"></svg>
</button>

app/views/application/_navigation.html.erb
<%= content_tag :div, class: "c-navbar", id: 'main-nav', data: { controller: "navbar" } do %>
  <%= content_tag :div, class: "c-navbar__section c-navbar__section--logo" do %>
    <span class="c-navbar__logo">
      <%= link_to current_user ? home_path : root_path do %>
        <%= logo %>
      <% end %>
    </span>
  <% end %>
  <%= content_tag :div, class: "c-navbar__section c-navbar__section--filler" do %>
    <!-- Spacer needed for layout purposes -->
    <div></div>
  <% end %>
  <%= content_tag :div, class: "c-navbar__section" do %>
    <div class="c-nav">
      <% if Pundit.policy(current_user, :show_manage).show? %>
        <%= link_to "Manage", manage_root_path, class: "c-nav__item", data: { cy: "manage" } %>
      <% end %>
      <% if current_user %>
        <%= link_to "Sign out", session_path, method: :delete, class: "c-nav__item", data: { cy: "sign-out" } %>
      <% else %>
        <%= remote_modal_link "Sign in", new_session_path, classes: "c-nav__item", data: {cy: "sign-in"} %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/application/_session_pages_layout.html.erb
<div class="l-main l-main--padded">
  <div class="l-container">
    <div class="l-row l-row--center-xs">
      <div class="l-col-xs-26 l-col-sm-14 l-col-md-12 l-col-lg-10">
        <%= yield %>
      </div>
    </div>
  </div>
</div>